### ISSUE TITLE
Starting under windows does not work

### ISSUE THREAD

**Issue by SebulonIsme** [jahshaka/VR#169]
The starting image appears.
Then Windows tells me, JahshakaVR doesn't work any more.

**Comment by iKlsR** [comment]
Hi @SebulonIsme, are you compiling from source or using a prebuilt exe? If the former, can you look in your build directory and post the contents of the log file here? If not, can you launch in debug mode and share a screenshot of the debug window?

**Comment by iKlsR** [comment]
In fact, we will do a new release very soon, you might have found an old bug in the master branch. The latest code can be found in the `dev` branch, try building that instead. https://github.com/jahshaka/VR/tree/dev, will update the readme for newcomers.

**Comment by SebulonIsme** [comment]
It was indeed the master branch. I don't have the skills to get into debug mode - but I'm glad you are looking into it. :-)

**Comment by iKlsR** [comment]
Hey @SebulonIsme , we have a new release out, can you give this a try again? Thanks! Feel free to reach out to us with any issues or suggestions.
