### ISSUE TITLE
Building on Linux fails

### ISSUE THREAD

**Issue by prokoudine** [jahshaka/VR#203]
I have assimp dev package installed on Debian Unstable, and yet:

 CMake Error at CMakeLists.txt:11 (include):
   include could not find load file:

     GnuInstallDirs

 CMake Error at irisgl/CMakeLists.txt:20 (add_subdirectory):
   The source directory

     /home/user/path/jahshaka/irisgl/src/assimp

   does not contain a CMakeLists.txt file.

 CMake Error at CMakeLists.txt:296 (set_target_properties):
   set_target_properties Can not find target to add properties to: assimp

**Comment by njbrown** [comment]
Hey,

You can fix the GnuInstallDirs issue by removing that line in the CMakeLists.txt file for now. I'll fix this in a pr.
As for assimp, it's a submodule. Pull it down by doing:
`git submodule update --init --recursive`

**Comment by prokoudine** [comment]
That got me further, and then:

/home/user/soft/graphics/jahshaka/irisgl/src/graphics/../vr/../libovr/Include/Extras/OVR_CAPI_Util.h:11:10: fatal error: OVR_CAPI.h: No such file or directory
 #include "OVR_CAPI.h"
          ^~~~~~~~~~~~
compilation terminated.

**Comment by iKlsR** [comment]
@prokoudine Sorry for the delay in getting back to you. Can you try again, this was fixed.
