### ISSUE TITLE
Compiling for Windows 10

### ISSUE THREAD

**Issue by Mitra-M** [jahshaka/VR#234]
OS = Win10
QT Version =5.9.4
Qtcreator Version  = 4.5

I can't run this project for Win10, also I can't compile that.

You said:

>  **Build steps**
> 
> Stable (usually old releases are available by default), for up to date code, **checkout the dev branch instead of master**
> 
> Clone the repo from the project page or download a zipped copy of the source for a specific version from the Releases tab
> Open the .pro file in Qt Creator
> Run the solution
>  

But there is not any .pro file in the [dev branch](https://github.com/jahshaka/VR/tree/dev) files. 
(also old [master branch](https://github.com/jahshaka/VR) gets many errors)

How to install/build Jahshaka for Win10?

Thanks.

**Comment by iKlsR** [comment]
Hi @Mitra-M, we will be updating the branch and doing a release today. We switched to cmake sometime back and the build instructions will be updated accordingly. You can follow the instructions just about the same but you will need to install CMake as well as doing a `git submodule update --init --recursive` to get the dependencies and then opening the `CMakeLists.txt` file with Qt Creator.

Also 5.9.4 introduces a cmake bug, I'd recommend downgrading to 5.9.3.

**Comment by Mitra-M** [comment]
Thank you.
