### ISSUE TITLE
curated list of excellent work made with Jahshaka

### ISSUE THREAD

**Issue by nitrofurano** [jahshaka/VR#277]
Where can we find a curated list of excellent work made with Jahshaka?
Sharing it would be great because it would boost Jahshaka visibility and popularity a lot!

**Comment by iKlsR** [comment]
Hi there @nitrofurano. We are still in heavy development so not much to see yet unfortunately as it relates to polished scenes. We do have some cool stuff that users can play with currently. Our next release will have more content as we improve the stability of the app and add more features tuned for virtual reality. For now what we can showcase is hosted at https://www.jahfx.com/.

**Comment by nitrofurano** [comment]
thanks! :)
