### ISSUE TITLE
.deb or ppa with Jahshaka 3.0

### ISSUE THREAD

**Issue by nitrofurano** [jahshaka/VR#287]
How can i install Jahshaka 3.0 (or the very last version) on GNU/LInux (specially on Ubuntu, Debian, etc.), without having to compile sources?

is there a .deb package or ppa repository available? i’m struggling a lot finding it...

thanks in advance! :)

**Comment by iKlsR** [comment]
Hi again, Jahshaka is still in alpha. We don't currently publish releases anywhere except sourceforge and our releases page. https://github.com/jahshaka/VR/releases. There is a build for linux available there, we also have another release (0.6.0) coming out in a day or two. 

Going forward, seeing as there are people interested we'll also provide a deb and snap for 0.7.0, thanks for your interest in the project.

**Comment by jahshaka** [comment]
now that 0.7.3 is finished we are going to submit to the ubuntu software center and hopefully we can get listed there for easy installation !
